MindWise/Controllers/CNPController.cs
using DAL.Models;
using DAL.Repository;
using DAL.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MindWise.Controllers
{
    public class CNPController : Controller
    {
        // GET: CNP
        public ActionResult Index()
        {
            return View();
        }
        public JsonResult GetCVVLDG(JQueryDataTableParamModel jModel, string SerchBy)
        {
            try
            {
                var result = UserRepository.GetCVVLDG(Convert.ToInt32(UserSession.ClientID), SerchBy, jModel.iDisplayStart, jModel.iDisplayLength);
                int? totalRecord = result.Count > 0 ? result[0].TotalRecords : 0;
                var CVVLDG = result.Select(row => new string[]
                         {
                            Convert.ToString(row.FirstName),//0
                            Convert.ToString(row.LastName),//1
                            Convert.ToString(row.Address),//2
                            Convert.ToString(row.Price),//3
                            Convert.ToString(row.City),//4
                            Convert.ToString(row.STATE),//5
                            Convert.ToString(row.Zip),//6
                            Convert.ToString(row.DOB),//7
                            Convert.ToString(row.Phone),//8
                            Convert.ToString(row.Gender),//9
                            Convert.ToString(row.SSN),//10
                            Convert.ToString(row.DateADDED),//11
                         });
                return Json(new
                {
                    iTotalRecords = totalRecord,
                    iTotalDisplayRecords = totalRecord,
                    aaData = CVVLDG
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {

                throw;
            }

        }
    }
}

MindWise/Controllers/CPController.cs
using DAL.Models;
using DAL.Repository;
using DAL.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MindWise.Controllers
{
    public class CPController : Controller
    {
        // GET: CP
        public ActionResult Index()
        {
            return View();
        }
        public JsonResult GetDUMPSLDG(JQueryDataTableParamModel jModel,string SerchBy)
        {
            try
            {
                var result = UserRepository.GetDUMPSLDG(Convert.ToInt32(UserSession.ClientID), SerchBy, jModel.iDisplayStart, jModel.iDisplayLength);
                int? totalRecord = result.Count > 0 ? result[0].TotalRecords : 0;
                var DUMPSLDG = result.Select(row => new string[]
                         {
                            Convert.ToString(row.Tracks),//0
                            Convert.ToString(row.Price),//1
                            Convert.ToString(row.Refundable),//2
                            Convert.ToString(row.STATE),//3
                            Convert.ToString(row.City),//4
                            Convert.ToString(row.Zip),//5
                         });
                return Json(new
                {
                    iTotalRecords = totalRecord,
                    iTotalDisplayRecords = totalRecord,
                    aaData = DUMPSLDG
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {

                throw;
            }

        }
    }
}

MindWise/Controllers/DashboardController.cs
using DAL.Entities;
using DAL.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAL.Utility;
using DAL.Models;

namespace MindWise.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Dashboard
        public ActionResult Index()
        {
            try
            {
                var result = DashboardRepository.GetCardClass(Convert.ToInt32(UserSession.ClientID));
                return View(result);
            }
            catch (Exception)
            {

                throw;
            }
        }
    }
}

MindWise/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MindWise.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
} 

MindWise/Controllers/LoginController.cs
using DAL.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAL.Repository;
using DAL.Models;
using DAL.Entities;

namespace MindWise.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login

        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public JsonResult Index(LoginModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var result = UserRepository.ValidUser(model.UserName, model.Password);
                    if (result!=null)
                    {
                        SetSession(result);
                        return Json("1", JsonRequestBehavior.AllowGet);
                    }
                }
                return Json("0", JsonRequestBehavior.AllowGet);

            }
            catch (Exception)
            {
                throw;
            }
        }
        private void SetSession(User user)
        {
            UserSession.UserName = user.UserName;
            UserSession.Email = user.Email;
            UserSession.UserID = user.UserID;
            UserSession.ClientID = user.ClientID;
        }
        [HttpGet]
        public ActionResult LogOut()
        {
            try
            {
                Session.Abandon();
                Session.Clear();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}

MindWise/Controllers/SignUpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MindWise.Controllers
{
    public class SignUpController : Controller
    {
        // GET: SignUp
        public ActionResult Index()
        {
            return View();
        }
    }
}

MindWise/Views/CNP/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Scripts/CNP/CNP.js"></script>
<div class="row">
    <div class="col-lg-12 portlets ui-sortable">
        <div class="panel">
            <div class="panel-header panel-controls ui-sortable-handle">
                <h3><i class="fa fa-table"></i>CNP (CARD NOT PRESENT)</h3>
                <div class="control-btn"><a href="#" class="panel-reload hidden"><i class="icon-reload"></i></a><a class="hidden" id="dropdownMenu1" data-toggle="dropdown"><i class="icon-settings"></i></a><ul class="dropdown-menu pull-right" role="menu" aria-labelledby="dropdownMenu1"><li><a href="#">Action</a></li><li><a href="#">Another action</a></li><li><a href="#">Something else here</a></li></ul><a href="#" class="panel-popout hidden tt" title="Pop Out/In"><i class="icons-office-58"></i></a><a href="#" class="panel-maximize hidden"><i class="icon-size-fullscreen"></i></a><a href="#" class="panel-toggle"><i class="fa fa-angle-down"></i></a><a href="#" class="panel-close"><i class="icon-trash"></i></a></div>
            </div>
            <div class="row">
                <div class="col-md-6">
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <div class="col-sm-12">
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <div class="col-sm-12">
                            <input type="text" id="txtSearchCNP" class="form-control" placeholder="Search">
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <div class="col-sm-12">
                            <button type="button" id="btnSearchCNP" class="btn btn-md btn-default">Search</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel-content pagination2 table-responsive">
                @Html.Partial("~/Views/PartialView/CVVLDG.cshtml")
            </div>
        </div>
    </div>
</div>

MindWise/Views/CP/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Scripts/CP/CP.js"></script>
<div class="row">
    <div class="col-lg-12 portlets ui-sortable">
        <div class="panel">
            <div class="panel-header panel-controls ui-sortable-handle">
                <h3><i class="fa fa-table"></i>CP (CARD PRESENT)</h3>
                <div class="control-btn"><a href="#" class="panel-reload hidden"><i class="icon-reload"></i></a><a class="hidden" id="dropdownMenu1" data-toggle="dropdown"><i class="icon-settings"></i></a><ul class="dropdown-menu pull-right" role="menu" aria-labelledby="dropdownMenu1"><li><a href="#">Action</a></li><li><a href="#">Another action</a></li><li><a href="#">Something else here</a></li></ul><a href="#" class="panel-popout hidden tt" title="Pop Out/In"><i class="icons-office-58"></i></a><a href="#" class="panel-maximize hidden"><i class="icon-size-fullscreen"></i></a><a href="#" class="panel-toggle"><i class="fa fa-angle-down"></i></a><a href="#" class="panel-close"><i class="icon-trash"></i></a></div>
            </div>
            <div class="row">
                <div class="col-md-6">
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <div class="col-sm-12">
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <div class="col-sm-12">
                            <input type="text" id="txtSearchCP" class="form-control" placeholder="Search">
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <div class="col-sm-12">
                            <button type="button" id="btnSearchCP" class="btn btn-md btn-default">Search</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel-content pagination2 table-responsive">
                @Html.Partial("~/Views/PartialView/DUMPSLDG.cshtml")
            </div>
        </div>
    </div>
</div>

MindWise/Views/Dashboard/Index.cshtml
@model List<DAL.Entities.CardClass>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/Scripts/Dashboard/Dashboard.js"></script>

<div class="row">
    <div class="col-xlg-12 col-financial-stocks">
        <div class="panel">
            <div class="panel-header panel-controls">
                <h3><i class="fa fa-table"></i>Card Class</h3>
            </div>
            <div class="panel-content widget-full widget-stock stock1">
                <div class="tabs tabs-linetriangle">
                    <ul class="nav nav-tabs nav-4" role="tablist">
                        @foreach (var item in @Model)
                        {
                            <li class="CardDetails" role="tab" data-toggle="tab">
                                <a href="#microsoft-tab" id="microsoft" data-toggle="tab">
                                    <span class="title">@item.ClassName</span>
                                    <span class="c-gray"><strong>@item.CardCount</strong></span>
                                </a>
                            </li>

                        }
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xlg-2 col-small-stats">
    </div>
    <div class="col-xlg-6">
    </div>
</div>

MindWise/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MindWise/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MindWise/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

MindWise/Views/Login/Index.cshtml
@model DAL.Models.LoginModel
@using DAL.Utility;

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}
<script src="@Url.Content("~/Scripts/Login/Login.js")"></script>

<div class="row">
    <div class="col-sm-6 col-md-4 col-md-offset-4">
        <div class="account-wall">
            <i class="user-img icons-faces-users-03"></i>
            @*<form class="form-signin"  role="form">*@
            @using (Html.BeginForm("Index", "Login", FormMethod.Post, new { @class = "form-signin" }))
            {
                <div class="append-icon">
                    @Html.TextBoxFor(m => m.UserName, new { @class = "form-control form-white username", placeholder = "Username", name = "Username", required = "required" })
                    @*<input type="text" name="username" id="username" class="form-control form-white username" placeholder="Username" required>*@
                    <i class="icon-user"></i>
                </div>
                <div class="append-icon m-b-20">
                    @Html.TextBoxFor(m => m.Password, new { @class = "form-control form-white password", @placeholder = "Password", name = "Password", required = "required", @type = "password" })
                    @*<input type="password" name="password" class="form-control form-white password" placeholder="Password" required>*@
                    <i class="icon-lock"></i>
                </div>
                <button type="submit" id="submit-form" class="btn btn-lg btn-danger btn-block ladda-button" data-style="expand-left">Sign In</button>
            }
            <div class="social-btn">
                <button type="button" class="btn-fb btn btn-lg btn-block btn-primary"><i class="icons-socialmedia-08 pull-left"></i>Connect with Facebook</button>
                <button type="button" class="btn btn-lg btn-block btn-blue"><i class="icon-social-twitter pull-left"></i>Login with Twitter</button>
            </div>
            <div class="clearfix">
                <p class="pull-left m-t-20"><a id="password" href="#">Forgot password?</a></p>
                <p class="pull-right m-t-20">
                    @Html.ActionLink("New here? Sign up", "Index", "SignUp", null, null)
                </p>
            </div>
            @*</form>*@
            <form class="form-password" role="form">
                <div class="append-icon m-b-20">
                    <input type="password" name="password" class="form-control form-white password" placeholder="Password" required>
                    <i class="icon-lock"></i>
                </div>
                <button type="submit" id="submit-password" class="btn btn-lg btn-danger btn-block ladda-button" data-style="expand-left">Send Password Reset Link</button>
                <div class="clearfix">
                    <p class="pull-left m-t-20"><a id="login" href="#">Already got an account? Sign In</a></p>
                    <p class="pull-right m-t-20">
                        @Html.ActionLink("New here? Sign up", "Index", "SignUp", null, null)
                    </p>
                </div>
            </form>
        </div>
    </div>
</div>

MindWise/Views/PartialView/CVVLDG.cshtml
<div id="DataTables_Table_0_wrapper" class="dataTables_wrapper">
    <div class="row">
        <div class="col-sm-12">
            <table class="table table-striped" id="tblCVVLDG" role="grid" style="width:100%;">
                <thead>
                    <tr role="row">
                        <th>
                            First Name
                        </th>
                        <th>
                            Last Name
                        </th>
                        <th>
                            Address
                        </th>
                        <th>
                            Price
                        </th>
                        <th>
                            City
                        </th>
                        <th>
                            State
                        </th>
                        <th>
                            Zip
                        </th>
                        <th>
                            DOB
                        </th>
                        <th>
                            Phone
                        </th>
                        <th>
                            Gender
                        </th>
                        <th>
                            SSN
                        </th>
                        <th>
                            Date Added
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
</div>

MindWise/Views/PartialView/DUMPSLDG.cshtml
<div id="DataTables_Table_0_wrapper" class="dataTables_wrapper">
    <div class="row">
        <div class="col-sm-12">
            <table class="table table-striped" id="tblDUMPSLDG" role="grid" style="width:100%;">
                <thead>
                    <tr role="row">
                        <th>
                            Tracks
                        </th>
                        <th>
                            Price
                        </th>
                        <th>
                            Refundable
                        </th>
                        <th>
                            state
                        </th>
                        <th>
                            City
                        </th>
                        <th>
                            Zip
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
</div>

MindWise/Views/Shared/_LayoutLogin.cshtml
@using DAL.Utility;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>MindWise</title>
    <link rel="shortcut icon" href="../Assets/images/favicon.png">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="@Url.Content("~/Assets/css/style.css?v=" + AppSetting.Version + "")" rel="stylesheet" />
    <link href="@Url.Content("~/Assets/css/ui.css?v=" + AppSetting.Version + "")" rel="stylesheet" />
    <link href="@Url.Content("~/Assets/plugins/icheck/skins/all.css?v=" + AppSetting.Version + "")" rel="stylesheet" />
    <link href="@Url.Content("~/Assets/plugins/bootstrap-loading/lada.min.css?v=" + AppSetting.Version + "")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/jNotify.jquery.css?v=" + AppSetting.Version + "")" rel="stylesheet" />
    <script src="@Url.Content("~/Assets/plugins/jquery/jquery-3.1.0.min.js?v=" + AppSetting.Version + "")"></script>
    <script src="@Url.Content("~/Scripts/jNotify.jquery.js?v=" + AppSetting.Version + "")"></script>
    <script src="@Url.Content("~/Scripts/Common.js")"></script>
</head>
@{ 
    string html = string.Empty;
    if(Request.Url.AbsoluteUri.Contains("SignUp"))
    {
        html = "class='account separate-inputs boxed'  data-page='signup'";
    }
    else
    {
        html = "class='account separate-inputs'  data-page='login'";
    }

}
<body @Html.Raw(html)>
    <div class="container" id="login-block">
        @RenderBody()
        <p class="account-copyright">
            <span>Copyright © @DateTime.Now.Year</span><span> MindWise</span>.<span>All rights reserved.</span>
        </p>
    </div>
    <div id="account-builder" style="display:none;">
        <form class="form-horizontal" role="form">
            <div class="row">
                <div class="col-md-12">
                    <i class="fa fa-spin fa-gear"></i>
                    <h3><strong>Customize</strong> Login Page</h3>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="col-xs-8 control-label">Social Login</label>
                        <div class="col-xs-4">
                            <label class="switch m-r-20">
                                <input id="social-cb" type="checkbox" class="switch-input" checked>
                                <span class="switch-label" data-on="On" data-off="Off"></span>
                                <span class="switch-handle"></span>
                            </label>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="col-xs-8 control-label">Background Image</label>
                        <div class="col-xs-4">
                            <label class="switch m-r-20">
                                <input id="image-cb" type="checkbox" class="switch-input">
                                <span class="switch-label" data-on="On" data-off="Off"></span>
                                <span class="switch-handle"></span>
                            </label>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="col-xs-8 control-label">Background Slides</label>
                        <div class="col-xs-4">
                            <label class="switch m-r-20">
                                <input id="slide-cb" type="checkbox" class="switch-input">
                                <span class="switch-label" data-on="On" data-off="Off"></span>
                                <span class="switch-handle"></span>
                            </label>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="col-xs-8 control-label">User Image</label>
                        <div class="col-xs-4">
                            <label class="switch m-r-20">
                                <input id="user-cb" type="checkbox" class="switch-input">
                                <span class="switch-label" data-on="On" data-off="Off"></span>
                                <span class="switch-handle"></span>
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <input type="hidden" id="hdnAppUrl" value="@AppSetting.AppUrl" />
    @*<script src="@Url.Content("~/Scripts/jquery.min-1.12.4.js?v=" + AppSetting.Version + "")"></script>*@
    <script src="@Url.Content("~/Assets/plugins/jquery/jquery-migrate-3.0.0.min.js?v=" + AppSetting.Version + "")"></script>
    <script src="@Url.Content("~/Assets/plugins/gsap/main-gsap.min.js?v=" + AppSetting.Version + "")"></script>
    <script src="@Url.Content("~/Assets/plugins/tether/js/tether.min.js?v=" + AppSetting.Version + "")"></script>
    <script src="@Url.Content("~/Assets/plugins/bootstrap/js/bootstrap.min.js?v=" + AppSetting.Version + "")"></script>
    <script src="@Url.Content("~/Assets/plugins/icheck/icheck.min.js?v=" + AppSetting.Version + "")"></script>
    <script src="@Url.Content("~/Assets/plugins/backstretch/backstretch.min.js?v=" + AppSetting.Version + "")"></script>
    <script src="@Url.Content("~/Assets/plugins/bootstrap-loading/lada.min.js?v=" + AppSetting.Version + "")"></script>
    <script src="@Url.Content("~/Assets/plugins/jquery-validation/jquery.validate.min.js?v=" + AppSetting.Version + "")"></script>
    <script src="@Url.Content("~/Assets/plugins/jquery-validation/additional-methods.min.js?v=" + AppSetting.Version + "")"></script>
    <script src="@Url.Content("~/Assets/js/plugins.js?v=" + AppSetting.Version + "")"></script>
    <script src="@Url.Content("~/Assets/js/pages/login-v1.js?v=" + AppSetting.Version + "")"></script>

</body>
</html>

MindWise/Views/SignUp/Index.cshtml
@model DAL.Models.SignUpModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}
<div class="row">
    <div class="col-sm-6 col-md-6 col-md-offset-3">
        <div class="account-wall">
            <i class="user-img icons-faces-users-03"></i>
            <form class="form-signup" action="dashboard.html" role="form">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="append-icon">
                            @*<input type="text" name="firstname" id="firstname" class="form-control form-white firstname" placeholder="First Name" required autofocus>*@
                            @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control form-white firstname", @id = "firstname", @placeholder = "First Name", @name = "firstname", @required = "required", autofocus = "autofocus" })
                            <i class="icon-user"></i>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="append-icon">
                            @*<input type="text" name="lastname" id="lastname" class="form-control form-white lastname" placeholder="Last Name" required>*@
                            @Html.TextBoxFor(m => m.LastName, new { @class = "form-control form-white lastname", @id = "lastname", @placeholder = "Last Name", @name = "lastname", @required = "required" })
                            <i class="icon-user"></i>
                        </div>
                    </div>
                </div>
                <div class="append-icon">
                    @*<input type="email" name="email" id="email" class="form-control form-white email" placeholder="Email" required>*@
                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control form-white email", @id = "email", @placeholder = "Email", @name = "email", @required = "required" })
                    <i class="icon-envelope"></i>
                </div>
                <div class="append-icon">
                    @*<input type="password" name="password" id="password" class="form-control form-white password" placeholder="Password" required>*@
                    @Html.TextBoxFor(m => m.Password, new { @class = "form-control form-white password", @id = "password", @placeholder = "Password", @name = "password", @required = "required" })
                    <i class="icon-lock"></i>
                </div>
                <div class="append-icon m-b-20">
                    @*<input type="password" name="password" id="password2" class="form-control form-white password2" placeholder="Repeat Password" required>*@
                    @Html.TextBoxFor(m => m.ConfirmPassword, new { @class = "form-control form-white password2", @id = "password2", @placeholder = "Repeat Password", @name = "password", @required = "required" })

                    <i class="icon-lock"></i>
                </div>
                <div class="terms option-group">
                    <label for="terms" class="m-t-10">
                        <input type="checkbox" name="terms" id="terms" data-checkbox="icheckbox_square-blue" required />
                        I agree with terms and conditions
                    </label>
                </div>
                <button type="submit" id="submit-form" class="btn btn-lg btn-dark m-t-20" data-style="expand-left">Register</button>
                @*<div class="social-btn">
                    <div class="row">
                        <div class="col-sm-6">
                            <button type="button" class="btn btn-lg btn-block btn-primary"><i class="fa fa-facebook pull-left"></i>Sign In with Facebook</button>
                        </div>
                        <div class="col-sm-6">
                            <button type="button" class="btn btn-lg btn-block btn-danger"><i class="fa fa-google pull-left"></i>Sign In with Google</button>
                        </div>
                    </div>
                </div>*@
                <div class="clearfix">
                    <p class="pull-right m-t-20">@Html.ActionLink("Already have an account? Sign In", "Index", "Login", null, null)</p>
                </div>
            </form>
        </div>
    </div>
</div>